### ISSUE TITLE
what if you dont have the true frontier?

### ISSUE THREAD

**Issue by timm** [ai-se/Spread-HyperVolume#1]

**Comment by vivekaxl** [comment]
I think the solution should be 
- the algorithm(for eg. DE) and run for 100X generation and/or 10X population (after removing the stopping criteria)
- remove all the dominated points from the final generation
- use the non dominated points as a true pareto frontier

**Comment by timm** [comment]
no nope no

not all models grant access to the full pareto frontier

need an engineering solution. when full frontier not known, it uses the two extreme points of the known sample from all the treatments

**Comment by vivekaxl** [comment]
What you are saying is absolutely correct!
- I have changed the code so that the code doesn't crash and uses the extreme points of the available solution set

But, if we know that the full frontier is not known...we should refrain from using spread as a performance measure and use hypervolume instead. 
Personally I like Joe's chart (for convergence) along with hypervolume. I saw a nice representation
![screenshot 2015-10-27 23 18 17](https://cloud.githubusercontent.com/assets/6147456/10778943/2002b6a8-7d01-11e5-8abf-35bbef552c28.png)
 in http://researchers.lille.inria.fr/~brockhof/publicationListFiles/bth2015a.pdf

These chart are called data profiles in the GECCO community (I didn't know about this). 

Once we see this graphs we can easily say which algorithm is doing better and this is because these figure encapsulates the number of evaluation required by an algorithm to get to the target value.

**Comment by timm** [comment]
detail: if you have results from n optimizers, you need the extreme points from **all** the data sets in the study

t

**Comment by amritbhanu** [comment]
@vivekaxl what do you mean exactly by two extreme points?

**Comment by vivekaxl** [comment]
Check out http://www.iitk.ac.in/kangal/Deb_NSGA-II.pdf pg 188
